[package]
name = "keyweave"
version = "0.2.2"
edition = "2021"
authors = ["Bart van der Braak <bart@vanderbraak.nl>"]
keywords = ["azure", "keyvault", "env"]
description = "Fetches secrets from Azure Key Vault and weaves them into a convenient .env file"
license = "GPL-3.0"
documentation = "https://docs.rs/keyweave"
repository = "https://github.com/bartvdbraak/keyweave/"

[dependencies]
azure_identity = "0.17.0"
azure_security_keyvault = "0.17.0"
clap = { version = "4.4.7", features = ["derive"] }
futures = "0.3.29"
tokio = {version = "1.33.0", features = ["full"]}

[target.'cfg(all(target_os = "linux", any(target_env = "musl", target_arch = "arm", target_arch = "aarch64")))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }