[package]
name = "keyweave"
version = "0.1.0"
edition = "2021"

[dependencies]
azure_identity = "0.17.0"
azure_security_keyvault = "0.17.0"
azure_core = { version = "0.17.0", features = ["enable_reqwest_rustls"] }
clap = { version = "4.4.7", features = ["derive"] }
futures = "0.3.29"
tokio = {version = "1.33.0", features = ["full"]}
